//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace acheoOnibusAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class getViagens
    {
        public int idViagem { get; set; }
        public int sentidoViagem { get; set; }
        public string origem { get; set; }
        public string destino { get; set; }
        public int idItinerarioFK { get; set; }
    }
}
