//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace acheoOnibusAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblItinerario
    {
        public tblItinerario()
        {
            this.tblOnibusItinerario = new HashSet<tblOnibusItinerario>();
            this.tblViagem = new HashSet<tblViagem>();
        }
    
        public int idItinerario { get; set; }
        public decimal tarifa { get; set; }
        public string numero { get; set; }
    
        public virtual ICollection<tblOnibusItinerario> tblOnibusItinerario { get; set; }
        public virtual ICollection<tblViagem> tblViagem { get; set; }
    }
}
