//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace acheoOnibusAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblOnibus
    {
        public tblOnibus()
        {
            this.tblOnibusItinerario = new HashSet<tblOnibusItinerario>();
        }
    
        public int idOnibus { get; set; }
        public string placa { get; set; }
        public string latitude { get; set; }
        public string longitude { get; set; }
        public int numeroOnibus { get; set; }
        public double velocidade { get; set; }
        public int sentidoViagem { get; set; }
    
        public virtual ICollection<tblOnibusItinerario> tblOnibusItinerario { get; set; }
    }
}
